//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 04:27:56 PM CEST 
//


package org.svv.acmate.model.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Method" type="{http://acmate.svv.org/configuration}AuthenticationMethod"/>
 *         &lt;element name="LogInURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LogoutURLSubfix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="userFieldName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="passwordFieldName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "method",
    "logInURL",
    "logoutURLSubfix"
})
@XmlRootElement(name = "Authentication")
public class Authentication {

    @XmlElement(name = "Method", required = true)
    @XmlSchemaType(name = "string")
    protected AuthenticationMethod method;
    @XmlElement(name = "LogInURL", required = true)
    protected String logInURL;
    @XmlElement(name = "LogoutURLSubfix", required = true)
    protected String logoutURLSubfix;
    @XmlAttribute(name = "userFieldName")
    protected String userFieldName;
    @XmlAttribute(name = "passwordFieldName")
    protected String passwordFieldName;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationMethod }
     *     
     */
    public AuthenticationMethod getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationMethod }
     *     
     */
    public void setMethod(AuthenticationMethod value) {
        this.method = value;
    }

    /**
     * Gets the value of the logInURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogInURL() {
        return logInURL;
    }

    /**
     * Sets the value of the logInURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogInURL(String value) {
        this.logInURL = value;
    }

    /**
     * Gets the value of the logoutURLSubfix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogoutURLSubfix() {
        return logoutURLSubfix;
    }

    /**
     * Sets the value of the logoutURLSubfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogoutURLSubfix(String value) {
        this.logoutURLSubfix = value;
    }

    /**
     * Gets the value of the userFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFieldName() {
        return userFieldName;
    }

    /**
     * Sets the value of the userFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFieldName(String value) {
        this.userFieldName = value;
    }

    /**
     * Gets the value of the passwordFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordFieldName() {
        return passwordFieldName;
    }

    /**
     * Sets the value of the passwordFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordFieldName(String value) {
        this.passwordFieldName = value;
    }

}
