/*******************************************************************************
 * Copyright (c) 2016, SVV Lab, University of Luxembourg
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * 3. Neither the name of acmate nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 04:27:56 PM CEST 
//


package org.svv.acmate.model.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Method" type="{http://acmate.svv.org/configuration}AuthenticationMethod"/>
 *         &lt;element name="LogInURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LogoutURLSubfix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="userFieldName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="passwordFieldName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "method",
    "logInURL",
    "logoutURLSubfix"
})
@XmlRootElement(name = "Authentication")
public class Authentication {

    @XmlElement(name = "Method", required = true)
    @XmlSchemaType(name = "string")
    protected AuthenticationMethod method;
    @XmlElement(name = "LogInURL", required = true)
    protected String logInURL;
    @XmlElement(name = "LogoutURLSubfix", required = true)
    protected String logoutURLSubfix;
    @XmlAttribute(name = "userFieldName")
    protected String userFieldName;
    @XmlAttribute(name = "passwordFieldName")
    protected String passwordFieldName;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationMethod }
     *     
     */
    public AuthenticationMethod getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationMethod }
     *     
     */
    public void setMethod(AuthenticationMethod value) {
        this.method = value;
    }

    /**
     * Gets the value of the logInURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogInURL() {
        return logInURL;
    }

    /**
     * Sets the value of the logInURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogInURL(String value) {
        this.logInURL = value;
    }

    /**
     * Gets the value of the logoutURLSubfix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogoutURLSubfix() {
        return logoutURLSubfix;
    }

    /**
     * Sets the value of the logoutURLSubfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogoutURLSubfix(String value) {
        this.logoutURLSubfix = value;
    }

    /**
     * Gets the value of the userFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFieldName() {
        return userFieldName;
    }

    /**
     * Sets the value of the userFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFieldName(String value) {
        this.userFieldName = value;
    }

    /**
     * Gets the value of the passwordFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordFieldName() {
        return passwordFieldName;
    }

    /**
     * Sets the value of the passwordFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordFieldName(String value) {
        this.passwordFieldName = value;
    }

}
