//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 04:27:56 PM CEST 
//


package org.svv.acmate.model.config;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthenticationMethod.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AuthenticationMethod">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Credential"/>
 *     &lt;enumeration value="HTTP Basic"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AuthenticationMethod")
@XmlEnum
public enum AuthenticationMethod {

    @XmlEnumValue("Credential")
    CREDENTIAL("Credential"),
    @XmlEnumValue("HTTP Basic")
    HTTP_BASIC("HTTP Basic");
    private final String value;

    AuthenticationMethod(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AuthenticationMethod fromValue(String v) {
        for (AuthenticationMethod c: AuthenticationMethod.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
