//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.07 at 09:19:42 AM CEST 
//


package org.svv.acmate.model.filters;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://acmate.svv.org/filters}URLPattern"/>
 *         &lt;element ref="{http://acmate.svv.org/filters}MethodPattern"/>
 *         &lt;element ref="{http://acmate.svv.org/filters}StatusCodePattern"/>
 *         &lt;element ref="{http://acmate.svv.org/filters}ContentPattern"/>
 *       &lt;/sequence>
 *       &lt;attribute name="permission" type="{http://acmate.svv.org/filters}Permission" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "urlPattern",
    "methodPattern",
    "statusCodePattern",
    "contentPattern"
})
@XmlRootElement(name = "Filter")
public class Filter {
	
	public static final String FILTER_PERMISSION_ALLOWED = "allowed";
	public static final String FILTER_PERMISSION_DENIED = "denied";
	public static final String FILTER_PERMISSION_UNKNOWN = "";

    @XmlElement(name = "URLPattern", required = true)
    protected URLPattern urlPattern;
    @XmlElement(name = "MethodPattern", required = true)
    protected MethodPattern methodPattern;
    @XmlElement(name = "StatusCodePattern", required = true)
    protected StatusCodePattern statusCodePattern;
    @XmlElement(name = "ContentPattern", required = true)
    protected List<ContentPattern> contentPattern;
    @XmlAttribute(name = "permission")
    protected String permission;

    /**
     * Gets the value of the urlPattern property.
     * 
     * @return
     *     possible object is
     *     {@link URLPattern }
     *     
     */
    public URLPattern getURLPattern() {
        return urlPattern;
    }

    /**
     * Sets the value of the urlPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link URLPattern }
     *     
     */
    public void setURLPattern(URLPattern value) {
        this.urlPattern = value;
    }

    /**
     * Gets the value of the methodPattern property.
     * 
     * @return
     *     possible object is
     *     {@link MethodPattern }
     *     
     */
    public MethodPattern getMethodPattern() {
        return methodPattern;
    }

    /**
     * Sets the value of the methodPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodPattern }
     *     
     */
    public void setMethodPattern(MethodPattern value) {
        this.methodPattern = value;
    }

    /**
     * Gets the value of the statusCodePattern property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCodePattern }
     *     
     */
    public StatusCodePattern getStatusCodePattern() {
        return statusCodePattern;
    }

    /**
     * Sets the value of the statusCodePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCodePattern }
     *     
     */
    public void setStatusCodePattern(StatusCodePattern value) {
        this.statusCodePattern = value;
    }

    /**
     * Gets the value of the contentPattern property.
     * 
     * @return
     *     possible object is
     *     {@link ContentPattern }
     *     
     */
    public List<ContentPattern> getContentPattern() {
//    	if (contentPattern == null) {
//            contentPattern = new ArrayList<ContentPattern>();
//        }
        return contentPattern;
    }
    
    public String getContentPatternString() {
    	String contentPatternString = "";
    	
    	if(contentPattern != null) {
    		for(ContentPattern pattern : contentPattern) {
    			contentPatternString += ("(" + pattern.getValue() + "," + pattern.isMatched() + ')');    			
    		}
    	}
    	
    	return contentPatternString;
    }

    /**
     * Sets the value of the contentPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentPattern }
     *     
     */
    public void setContentPattern(List<ContentPattern> value) {
        this.contentPattern = value;
    }

    /**
     * Gets the value of the permission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermission() {
        return permission;
    }

    /**
     * Sets the value of the permission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermission(String value) {
        this.permission = value;
    }

}
