//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.07 at 09:19:42 AM CEST 
//


package org.svv.acmate.model.filters;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.svv.acmate.model.filters package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.svv.acmate.model.filters
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Filters }
     * 
     */
    public Filters createFilters() {
        return new Filters();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link URLPattern }
     * 
     */
    public URLPattern createURLPattern() {
        return new URLPattern();
    }

    /**
     * Create an instance of {@link MethodPattern }
     * 
     */
    public MethodPattern createMethodPattern() {
        return new MethodPattern();
    }

    /**
     * Create an instance of {@link StatusCodePattern }
     * 
     */
    public StatusCodePattern createStatusCodePattern() {
        return new StatusCodePattern();
    }

    /**
     * Create an instance of {@link ContentPattern }
     * 
     */
    public ContentPattern createContentPattern() {
        return new ContentPattern();
    }

}
