//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 03:58:52 PM CEST 
//


package org.svv.xinput;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inputType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="inputType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PARAM_URL"/>
 *     &lt;enumeration value="PARAM_BODY"/>
 *     &lt;enumeration value="PARAM_COOKIE"/>
 *     &lt;enumeration value="PARAM_XML"/>
 *     &lt;enumeration value="PARAM_XML_ATTR"/>
 *     &lt;enumeration value="PARAM_MULTIPART_ATTR"/>
 *     &lt;enumeration value="PARAM_JSON"/>
 *     &lt;enumeration value="PARAM_UNKNOWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "inputType")
@XmlEnum
public enum InputType {

    PARAM_URL,
    PARAM_BODY,
    PARAM_COOKIE,
    PARAM_XML,
    PARAM_XML_ATTR,
    PARAM_MULTIPART_ATTR,
    PARAM_JSON,
    PARAM_UNKNOWN;

    public String value() {
        return name();
    }

    public static InputType fromValue(String v) {
        return valueOf(v);
    }

}
