package org.svv.acmate.gui;

import org.svv.GlobalConstants;

/**
 *
 * @author cdnguyen
 */
public class OptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form OptionPanel
     */
    public OptionPanel() {
        initComponents();
        
        if (GlobalConstants.FOLLOW_REDIRECTION)
        	bttnFollowRedirectons.setSelected(true);
        else 
        	bttnFollowRedirectons.setSelected(false);

        if (GlobalConstants.GROUP_REQUEST_TO_RESOURCE)
        	bttnGroupRequests.setSelected(true);
        else 
        	bttnGroupRequests.setSelected(false);
        
        if (GlobalConstants.J48_BINARY_SPLITTING)
        	bttnJ48UseBinarySplitting.setSelected(true);
        else 
        	bttnJ48UseBinarySplitting.setSelected(false);
        
        if (GlobalConstants.REMOVE_ENDING_SLASH)
        	bttnRemoveSlash.setSelected(true);
        else 
        	bttnRemoveSlash.setSelected(false);
        
//        if (GlobalConstants.USE_SERVER_RESTORE_CMD) {
//        	bttnUseServerRestoreCommand.setSelected(true);
//    		txtServerRestoreCmd.setEnabled(true);
//    		txtServerRestoreCmd.setEditable(true);
//    		bttnApply.setEnabled(true);
//    		bttnClear.setEnabled(true);
//        }
//        else {
//        	bttnUseServerRestoreCommand.setSelected(false);
//    		txtServerRestoreCmd.setEnabled(false);
//    		txtServerRestoreCmd.setEditable(false);
//            bttnApply.setEnabled(false);
//            bttnClear.setEnabled(false);
//        }
        
//        if (GlobalConstants.IGNORE_FAILED_LOGIN) 
//        	bttnIgnoreFailedLoggedIn.setSelected(true);
//        else
//        	bttnIgnoreFailedLoggedIn.setSelected(false);
        
        disableInLite();
    }

    /**
     * Disable some buttons that are not used in lite version
     */
    private void disableInLite(){
    	bttnJ48UseBinarySplitting.setEnabled(false);
    	bttnUseServerRestoreCommand.setEnabled(false);
    	bttnIgnoreFailedLoggedIn.setEnabled(false);
    	txtServerRestoreCmd.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bttnFollowRedirectons = new javax.swing.JToggleButton();
        bttnGroupRequests = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        bttnRemoveSlash = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        bttnJ48UseBinarySplitting = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        bttnUseServerRestoreCommand = new javax.swing.JToggleButton();
        bttnApply = new javax.swing.JButton();
        bttnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bttnIgnoreFailedLoggedIn = new javax.swing.JToggleButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ACMate Options"));

        jLabel1.setText("Follow server redirections:");

        jLabel2.setText("Group requests to resourse bases on parameters");

        bttnFollowRedirectons.setText("Yes/No");
        bttnFollowRedirectons.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnFollowRedirectonsActionPerformed(evt);
            }
        });

        bttnGroupRequests.setText("Yes/No");
        bttnGroupRequests.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnGroupRequestsActionPerformed(evt);
            }
        });

        jLabel3.setText("Remove ending forward slash (/) from URLs");

        bttnRemoveSlash.setText("Yes/No");
        bttnRemoveSlash.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnRemoveSlashActionPerformed(evt);
            }
        });

        jLabel4.setText("J48 - Use binary splitting to reduce # of rules");
        jLabel4.setEnabled(false);

        bttnJ48UseBinarySplitting.setText("Yes/No");
        bttnJ48UseBinarySplitting.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnJ48UseBinarySplittingActionPerformed(evt);
            }
        });
        bttnJ48UseBinarySplitting.setEnabled(false);
        
        jLabel5.setText("<html>Restore the target server using the administrative command. <br>" + 
        				"USE with CARE! <br>" +
        				"The below command will be executed before each test session.<br><br>" + 
        				"Restore target server command:<br></html>");
        
        bttnUseServerRestoreCommand.setText("Yes/No");
        bttnUseServerRestoreCommand.addActionListener(new java.awt.event.ActionListener() {
        	@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
        		bttnUseServerRestoreCommandActionPerformed(evt);
        	}
        });
        jLabel5.setEnabled(false);
        bttnUseServerRestoreCommand.setEnabled(false);
        
        txtServerRestoreCmd = new javax.swing.JTextField();

        bttnApply.setText("Apply");
        bttnApply.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
//                bttnApplyActionPerformed(evt);
            }
        });
        bttnApply.setEnabled(false);

        bttnClear.setText("Clear");
        bttnClear.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
//                bttnClearActionPerformed(evt);
            }
        });
        bttnClear.setEnabled(false);

        jLabel6.setText("<html> Ignore failed log-in in the test:<br> <br> Activate this option to do AC test for anonymous <br>user or blocked/limited access accounts </html>");
        jLabel6.setEnabled(false);

        bttnIgnoreFailedLoggedIn.setText("Yes/No");
        bttnIgnoreFailedLoggedIn.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
//                bttnIgnoreFailedLoggedInActionPerformed(evt);
            }
        });
        bttnIgnoreFailedLoggedIn.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5,javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                	.addComponent(bttnIgnoreFailedLoggedIn)
                	.addComponent(bttnFollowRedirectons)
                    .addComponent(bttnRemoveSlash)
                    .addComponent(bttnGroupRequests)
                    .addComponent(bttnJ48UseBinarySplitting)
                    .addComponent(bttnUseServerRestoreCommand)
                    .addComponent(txtServerRestoreCmd, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttnApply)
                        .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bttnFollowRedirectons))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bttnGroupRequests))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bttnRemoveSlash))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bttnJ48UseBinarySplitting))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bttnUseServerRestoreCommand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtServerRestoreCmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnApply)
                    .addComponent(bttnClear))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnIgnoreFailedLoggedIn))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void bttnFollowRedirectonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnFollowRedirectonsActionPerformed
        if (bttnFollowRedirectons.isSelected())
        	GlobalConstants.FOLLOW_REDIRECTION = true;
        else 
        	GlobalConstants.FOLLOW_REDIRECTION = false;
        	
    }//GEN-LAST:event_bttnFollowRedirectonsActionPerformed

    private void bttnGroupRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnGroupRequestsActionPerformed
        if (bttnGroupRequests.isSelected()){
        	GlobalConstants.GROUP_REQUEST_TO_RESOURCE = true;
        } else 
        	GlobalConstants.GROUP_REQUEST_TO_RESOURCE = false;
    }//GEN-LAST:event_bttnGroupRequestsActionPerformed

    private void bttnRemoveSlashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnRemoveSlashActionPerformed
    	if (bttnRemoveSlash.isSelected()){
    		GlobalConstants.REMOVE_ENDING_SLASH = true;
    	} else 
    		GlobalConstants.REMOVE_ENDING_SLASH = false;
    }//GEN-LAST:event_bttnRemoveSlashActionPerformed

    private void bttnJ48UseBinarySplittingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnJ48UseBinarySplittingActionPerformed
        if (bttnJ48UseBinarySplitting.isSelected())
        	GlobalConstants.J48_BINARY_SPLITTING = true;
        else
        	GlobalConstants.J48_BINARY_SPLITTING = false;
    }//GEN-LAST:event_bttnJ48UseBinarySplittingActionPerformed
    
    private void bttnUseServerRestoreCommandActionPerformed(java.awt.event.ActionEvent evt) {
    	if (bttnUseServerRestoreCommand.isSelected()) {
    		GlobalConstants.USE_SERVER_RESTORE_CMD = true;
    		txtServerRestoreCmd.setEnabled(true);
    		txtServerRestoreCmd.setEditable(true);
    		bttnApply.setEnabled(true);
    		bttnClear.setEnabled(true);
    	}
    	else {
    		GlobalConstants.USE_SERVER_RESTORE_CMD = false;
    		txtServerRestoreCmd.setEnabled(false);
    		txtServerRestoreCmd.setEditable(false);
    		bttnApply.setEnabled(false);
    		bttnClear.setEnabled(false);
    	}
    }

    private void bttnApplyActionPerformed(java.awt.event.ActionEvent evt) {                                          
        GlobalConstants.SERVER_RESTORE_CMD = txtServerRestoreCmd.getText();
    }                                         

    private void bttnClearActionPerformed(java.awt.event.ActionEvent evt) {                                          
        txtServerRestoreCmd.setText("");
    }                                         

    private void bttnIgnoreFailedLoggedInActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        if (bttnIgnoreFailedLoggedIn.isSelected()) 
        	GlobalConstants.IGNORE_FAILED_LOGIN = true;
        else
        	GlobalConstants.IGNORE_FAILED_LOGIN = false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnApply;
    private javax.swing.JButton bttnClear;
    private javax.swing.JToggleButton bttnFollowRedirectons;
    private javax.swing.JToggleButton bttnGroupRequests;
    private javax.swing.JToggleButton bttnJ48UseBinarySplitting;
    private javax.swing.JToggleButton bttnRemoveSlash;
    private javax.swing.JToggleButton bttnUseServerRestoreCommand;
    private javax.swing.JToggleButton bttnIgnoreFailedLoggedIn;
    private javax.swing.JTextField txtServerRestoreCmd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
