/*******************************************************************************
 * Copyright (c) 2016, SVV Lab, University of Luxembourg
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * 3. Neither the name of acmate nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *******************************************************************************/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.svv.acmate.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Vector;

import javax.swing.JOptionPane;
import org.svv.acmate.model.config.User;


/**
 *
 * @author cdnguyen
 */
public class UserDialog extends javax.swing.JDialog {
	
	private String userName;
	private String password;
	private String role;
		
	private int selectedOption = JOptionPane.OK_OPTION;
	private User currentUser;
	private RoleModel roleModel;

    /**
     * Creates new form UserDialog
     */
    public UserDialog(Vector<String> roles) {
        initComponents();
        currentUser = new User();
        setTitle("Add an user");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setModal(true);

        if (roles != null && roles.size() > 0) {
	        roleModel = new RoleModel(roles);
	        comboRoles.setModel(roleModel);
	        
	        // default
	        comboRoles.setSelectedIndex(0);
	        role = comboRoles.getItemAt(0);
        }
        
    }
    
    public UserDialog(User u, Vector<String> roles){
    	initComponents();
        currentUser = u;
        setTitle("Update user");
        btbAddOrUpdate.setText("Update");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setModal(true);
        
        txtUserName.setText(currentUser.getUsername());
        txtPassword.setText(currentUser.getPassword());
        
        role = currentUser.getRole();
        if (roles != null && roles.size() > 0) {
        	roleModel = new RoleModel(roles);
        	comboRoles.setModel(roleModel);
        	
        	for (int i = 0; i < roles.size(); i++){
        		if (role.equals(roles.get(i))){
        			comboRoles.setSelectedIndex(i);
        			break;
        		}
        	}
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboRoles = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        txtNewRole = new javax.swing.JTextField();
        btbAddOrUpdate = new javax.swing.JButton();
        bttnCancel = new javax.swing.JButton();

        jLabel1.setText("Username");

        addKeyListener(new MyKeyListener());
        
        jLabel2.setText("Password");

        jLabel3.setText("Role");
        
        txtNewRole.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				addNewRole();
			}
		});

//        comboRoles.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRoles.addActionListener(new MyComboActionListener());

        jLabel4.setText("New Role");

        btbAddOrUpdate.setText("Add");
        btbAddOrUpdate.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAddOrUpdateActionPerformed(evt);
            }
        });

        bttnCancel.setText("Cancel");
        bttnCancel.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboRoles, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserName)
                            .addComponent(txtNewRole)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 142, Short.MAX_VALUE)
                        .addComponent(btbAddOrUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewRole)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbAddOrUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );


        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Call to add a new role
     */
    protected void addNewRole() {
    	String tmp = txtNewRole.getText();
		if (tmp != null && !tmp.isEmpty()){
			for (String r :  roleModel.getExistingRoles()){
				if (tmp.equals(r)){
					JOptionPane.showMessageDialog(txtNewRole, "Role exists!");
					return;
				}
			}
			role = tmp;
			roleModel.addElement(role);
			comboRoles.setSelectedItem(role);
		}
	}

	private void btbAddOrUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAddOrUpdateActionPerformed
        currentUser.setUsername(txtUserName.getText());
        currentUser.setPassword(txtPassword.getText());
        currentUser.setRole(role);
        selectedOption = JOptionPane.OK_OPTION;
        this.setVisible(false);
    }
    
    
    private void bttnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	selectedOption = JOptionPane.CANCEL_OPTION;
    	this.setVisible(false);
    }  
    
    public int getSelectedOption() {
    	return selectedOption;
    }
  	
    public User getCurrentUser() {
		return currentUser;
	}  
    
    /**
     * 
     * @author cdnguyen
     *
     */
    private class MyComboActionListener implements java.awt.event.ActionListener{

		@Override
		public void actionPerformed(ActionEvent e) {
			role = (String) comboRoles.getSelectedItem();
		}
    }
    
    public class MyKeyListener implements KeyListener {

		@Override
		public void keyTyped(KeyEvent e) {
			// TODO Auto-generated method stub

		}

		@Override
		public void keyPressed(KeyEvent e) {
			// TODO Auto-generated method stub

		}

		@Override
		public void keyReleased(KeyEvent e) {
			// Check if the event is on the txtNewRole
			// check if the key is tab
			// then call addNewRole()

		}

	}
    
    /**
     * Model to handle roles
     * @author cdnguyen
     *
     */
    private class RoleModel extends javax.swing.DefaultComboBoxModel<String>{
    	
    	private Vector<String> existingRoles;

		public RoleModel(Vector<String> items) {
			super(items);
			existingRoles = items;
		}

		public Vector<String> getExistingRoles() {
			return existingRoles;
		}    
		
		
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbAddOrUpdate;
    private javax.swing.JButton bttnCancel;

    private javax.swing.JComboBox<String> comboRoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtNewRole;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables


}
